UPDATE buildings SET design_occupancy = 'Offices', nscp_edition_year = 'Pre-Code' WHERE id = 1;
UPDATE buildings SET design_occupancy = 'Offices', nscp_edition_year = 'Unable to identify' WHERE id = 2;
UPDATE buildings SET design_occupancy = 'Offices', nscp_edition_year = 'Unable to identify' WHERE id = 3;
UPDATE buildings SET design_occupancy = 'Offices', nscp_edition_year = '2010' WHERE id = 4;
UPDATE buildings SET design_occupancy = 'Offices', nscp_edition_year = '2010' WHERE id = 5;
UPDATE buildings SET design_occupancy = 'Public Assembly', nscp_edition_year = '2010' WHERE id = 6;
UPDATE buildings SET design_occupancy = 'Offices', nscp_edition_year = '2015' WHERE id = 7;
UPDATE buildings SET design_occupancy = 'Public Assembly', nscp_edition_year = '2015' WHERE id = 8;
UPDATE buildings SET design_occupancy = 'Public Assembly', nscp_edition_year = '2015' WHERE id = 9;
UPDATE buildings SET design_occupancy = 'Public Assembly', nscp_edition_year = '2015' WHERE id = 10;
UPDATE buildings SET design_occupancy = 'Public Assembly', nscp_edition_year = '2015' WHERE id = 11;
UPDATE buildings SET design_occupancy = 'Public Assembly', nscp_edition_year = '2015' WHERE id = 12;
UPDATE buildings SET design_occupancy = 'Public Assembly', nscp_edition_year = '2015' WHERE id = 13;
UPDATE buildings SET design_occupancy = 'Public Assembly', nscp_edition_year = '2015' WHERE id = 14;
UPDATE buildings SET design_occupancy = 'Public Assembly', nscp_edition_year = '1987' WHERE id = 15;
UPDATE buildings SET design_occupancy = 'Public Assembly', nscp_edition_year = '2015' WHERE id = 16;
UPDATE buildings SET design_occupancy = 'Public Assembly', nscp_edition_year = '2015' WHERE id = 17;
UPDATE buildings SET design_occupancy = 'Public Assembly', nscp_edition_year = '2015' WHERE id = 18;
UPDATE buildings SET design_occupancy = 'Public Assembly', nscp_edition_year = '2015' WHERE id = 19;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2015' WHERE id = 20;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2010' WHERE id = 21;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = 'Unable to identify' WHERE id = 22;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2015' WHERE id = 23;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2001' WHERE id = 24;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2010' WHERE id = 25;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2015' WHERE id = 26;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2010' WHERE id = 27;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2015' WHERE id = 28;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2010' WHERE id = 29;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2015' WHERE id = 30;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2001' WHERE id = 31;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2015' WHERE id = 32;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2010' WHERE id = 33;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2001' WHERE id = 34;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2015' WHERE id = 35;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2015' WHERE id = 36;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2010' WHERE id = 37;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2001' WHERE id = 38;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2015' WHERE id = 39;
UPDATE buildings SET design_occupancy = 'School', nscp_edition_year = '2015' WHERE id = 40;